name: cat_trivia
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  logger: ^1.1.0
  intl: ^0.17.0
  loading_gifs: ^0.3.0
  path_provider: ^2.0.10
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets: 
  - assets/icons/
